site_name: SPLENDID RESEARCH API Documentation
pages:
    - Overview: index.md
    - Panelist Transfer: panelist.md
    - Invite Requests: invites.md
    - Status: status.md
    - Redirects: redirect.md 
    - About: about.md
theme: readthedocs
